name: Publish package on GitHub Packages

on:
  release:
    types: [created]

env:
  NODE_AUTH_TOKEN: ${{ secrets.G_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.4
          registry-url: "https://npm.pkg.github.com"
          scope: "@kacpermichalik"
          always-auth: true

      - name: Install dependecies
        run: |
          npm ci

      - name: Build package
        run: |
          npm run package

      - name: Set npm config
        run: cd package && npm config set https://npm.pkg.github.com/:_authToken ${{ secrets.G_ACCESS_TOKEN }}

      - name: Set npm registry
        run: cd package && npm config set @kacpermichalik:registry https://npm.pkg.github.com

      - name: Publish pacakge
        run: cd package && npm publish @kacpermichalik:registry https://npm.pkg.github.com
